server:
  port: 8081

spring:
  application:
    name: climalert

  datasource:
    url: jdbc:h2:mem:climalert-db
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

climalert:
  scheduler:
    obtener-clima: "0 */5 * * * *"
    analizar-alertas: "0 * * * * *"

  weather:
    base-url: https://api.weatherapi.com/v1
    api-key: ${WEATHER_API_KEY:}
    location: "-34.6037,-58.3816"

mailtrap:
  base-url: https://send.api.mailtrap.io
  token: ${MAILTRAP_TOKEN:}
  from-email: ${MAILTRAP_FROM_EMAIL:hello@demomailtrap.co}
  from-name: Climalert
  category: Climalert Alert
  to-emails: ${MAILTRAP_TO_EMAILS:admin@clima.com,emergencias@clima.com,meteorologia@clima.com}